apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx-deployment
  labels:
    app: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - name: example-nginx
        image: nginx:latest