kind: Service
apiVersion: v1
metadata:
  name:  example-service
spec:
  selector:
    app: my-deployment
  # type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  TCP
    port:  80
    targetPort:  8080